### ISSUE TITLE
can't use enter to move through dialog

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#126] opened 2018-04-19 18:45 UTC
Maybe the other windows have focus (the drawing order fix)?

**Comment by bradallred** [comment] 2018-04-19 20:57
its a regressions from 1e1bcf9

`MakeDefault()` no longer sets the hot key globally since most of the time we dont want that. I'll update the Dialog window to `SetHotkey()` with a `True` value for being global.

**Comment by lynxlynxlynx** [comment] 2018-04-19 21:19
That doesn't sound like a good default.

**Comment by bradallred** [comment] 2018-04-19 21:20
thats why it was changed to be `False`

**Comment by lynxlynxlynx** [comment] 2018-04-19 21:22
I meant the reverse, the needed change looks both ugly and will have to spread elsewhere (cg suffers the same problem).

**Comment by bradallred** [comment] 2018-04-19 21:35
how about a parameter for it on `MakeDefault()` then? sound better?

I'm not sure about chargen does it actually require the enterkey to be sent to a background window or is it just coincidence that the window happens to be behind another? either way sometimes we need it global sometimes not. otherwise you would need an even more ugly and extensive approach of rebinding the key when the window above is closed.

**Comment by lynxlynxlynx** [comment] 2018-04-19 21:40
yes, that'd be much cleaner. As for cg, I don't know, it just doesn't work anymore hence testing is super annoying.

**Comment by bradallred** [comment] 2018-04-19 21:43
Ok, I'll change that and have a look at the CG requirements.

**Comment by bradallred** [comment] 2018-04-19 22:51
I actually dont see an issue in chargen. is it a specific window/step? or a game other than BG2?

**Comment by lynxlynxlynx** [comment] 2018-04-20 08:03
Everything besides gender needs manual intervention to enter its part of cg.

**Comment by bradallred** [comment] 2018-04-20 23:27
ok, I didnt realize those main buttons should react to enter. The ones I expected to still do so i didnt see the issue.

**Comment by bradallred** [comment] 2018-04-20 23:40
anything else?

**Comment by lynxlynxlynx** [comment] 2018-04-21 16:04
both work now, though in dialog there is an unfortunate side effect — enter also works when presented with a choice. It chooses the first option or crashes, visible if you let Jaheira talk to you (move near her cell) and then pressing enter (cb is null in EventMgr::DispatchEvent).

**Comment by lynxlynxlynx** [comment] 2018-04-21 16:53
That fixed the crash, while the defaulting remains.

**Comment by bradallred** [comment] 2018-04-21 18:23
i didnt notice the "default" because i tested with the first dialog before the "continue" window is opened and enter is inert as expected there. then we simply hide the window instead of closing it and since its a global hotkey it will happily trigger the button. we should probably properly close and reopen that "window" rather then hiding/unhiding. 

Edit: or disable the button

**Closed as completed** 2018-05-28 15:45 UTC
