### ISSUE TITLE
dialog: padding and vanishing issues when presented with choice

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#103] opened 2017-12-10 21:31 UTC
Minsc or Jaheira are examples. Scrolling the messagewindow when there's a choice to be made often causes the area with the choices to be pushed further down. Or that's how it appears, as usually the text leading to it vanishes and isn't present in the history. Something that's easier to reproduce than explain. 

Even just moving the mouse over the choices sometimes pushes them downward.

**Comment by bradallred** [comment] 2017-12-11 00:48
can you provide a save where I can see this?

I wonder if the history is getting trimmed during dialog. If so an easy fix that would probably also be a welcome feature would be to not trim history while in dialog mode. You could test that theory by disabling the trim and see if the issue remains.

**Comment by lynxlynxlynx** [comment] 2017-12-11 18:24
Just load chateau irenicus and talk to them. It takes a few tries, haven't found a reliable way to reproduce.

**Comment by bradallred** [comment] 2017-12-12 05:30
I haven't been able to reproduce since 4fe3f61, but I only tried a few times

**Comment by bradallred** [comment] 2018-04-17 03:14
I havent been able to reproduce this since the aforementioned history adjustment, so I'm closing this.

**Closed as completed by bradallred** 2018-04-17 03:14 UTC
