### ISSUE TITLE
Vanishing version label

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#57] opened 2017-08-20 12:00 UTC
Randomly clicking around the first window (soa/tob choice) often makes the version label (that we create) vanish. Reloading the window helps. It's also visible in the same case of Start2.py. Also in some other labels, which disappear when clicked on, but that might be a different issue.

One such example, easier to reproduce, is the inventory encumbrance labels, which we also create. I thought perhaps clicking on the bag button below them forces it infront, however just making the button locked or fakepressed doesn't fix this. Making it disabled helps, even though it's the wrong state, but it doesn't fix it completely and sometimes the labels clip the button bam ...

**Comment by bradallred** [comment] 2017-08-20 16:52
confirmed... and totally bizarre

**Comment by bradallred** [comment] 2017-08-20 19:15
I think I see what is happening. It looks like `View::AddSubviewInFrontOfView` is not declared virtual, so the "override" in `ScrollView` only works when this method is called from a pointer of type `ScrollView` (or subclass). if we call this from a `View` pointer we will execute `View::AddSubviewInFrontOfView` so then we end up with a `Label` that isn't properly embedded into the windows `contentView`.

I have yet to confirm this.

**Comment by lynxlynxlynx** [comment] 2017-08-20 19:57
Yeah, fixes the version labels. The inventory ones remain as-is. Could be some new code is not checking for all the button states (2x locked and 2x "fake").

**Comment by bradallred** [comment] 2017-08-20 20:10
yes, i'm sure the inventory issues are a separate issue. I'll close this.

**Closed as completed by bradallred** 2017-08-20 20:10 UTC
