### ISSUE TITLE
videos with subtitles crash

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#71] opened 2017-09-09 22:29 UTC
By the time they want to look at them with SubtitleAtFrame, subs is already garbage, not what was read from the table.

Could be my poor language skill, but isn't the IESubtitles instance wiped as soon as the scope is changed and the movie player is left with a reference to repurposed memory? I'll check tomorrow, too late now.

**Comment by bradallred** [comment] 2017-09-09 22:35
yeah, you are correct. the ivar shouldnt be a pointer, but just changing that isn't enough. `IESubtitles` needs a copy ctor defined to retain/copy the palette.

**Comment by bradallred** [comment] 2017-09-09 23:19
5f19153 ought to resolve the crashing, but probably going to be issues drawing on YUV videos. we would need to render the subs on the part of the window not covered by the video due to SDL 1.2's seeming inability to use an overlay in concert with standard blits.

I'm also not sure about black being the proper default bg color. for all I know it should be transparent.

theoretically this should work for RGB videos just fine now, but I don't know where to find one to test that with.

**Comment by lynxlynxlynx** [comment] 2017-09-10 09:46
Cool. This makes things better in the sense that subtitled videos don't crash immediately. Now they do as soon as trying to drawn the first character in SDLVideoDriver::BlitSurfaceClipped. The parameters look fine, but when it comes to the blit it breaks somewhere in SDL. At that point most of the rects used have zero dimensions because ClippedDrawingRect zeroed one and it propagated. It looks like it's because the drawingBuffer/bufrgn is smaller than the screen and y2 gets clipped in the intersect and then annulled. IOW it looks like we're trying to render the subtitles below the video, while the drawing code expects it over.

**Comment by lynxlynxlynx** [comment] 2017-09-10 09:50
MVE ones just aren't displayed. The bg2 intro video is an example, but don't forget to enable the config options when testing.

**Comment by lynxlynxlynx** [comment] 2017-09-10 22:09
So, BIKs work fine again, except the ones with subs. All visible in the intro 4. Plus the resurfaced window/event stuff if you try to run them from the video browser.

**Comment by bradallred** [comment] 2017-09-12 00:20
the event assertion was never solved. The problem is two fold:

1. the movie list window is displayed modally (maybe a reason for #44). AFICT we dont need it to be modal.
2. the modal window is set to be invisible (which is the real reason for the assert). We probably shouldn't allow this to happen.

**Comment by bradallred** [comment] 2017-09-12 00:34
I see that its the options window, so we probably do need that to be modal for other cases. The invisibility is due to the HideGUI invoked by `Interface::PlayMovie()` which is fine.

For now making the movie window modal seems to fix it.

**Comment by lynxlynxlynx** [comment] 2017-09-12 09:45
Yeah, the subs thing is gone. BIKs with subs are not drawing, so that's the only thing that remains afaics.

**Comment by bradallred** [comment] 2017-09-14 01:15
FYI BIK video subtitles don't work in master either (presumably for the same reason).

I've done a bit of trickery to make them work here, but they will only work when drawn outside the video so if the video is occupying the entire window height you will get nothing. It also comes with a huge performance penalty when plying BIK videos so I don't personally think it is worth it. We might be better off making this an SDL 2 only feature.

**Comment by lynxlynxlynx** [comment] 2017-09-14 10:01
Yeah, I already said they never did. But at least the video is displayed there, while not on this branch any more.

**Comment by bradallred** [comment] 2017-09-15 04:49
I was holding off committing/pushing that while i tried to improve performance enough to make them watchable. Only the software renderer on SDL 1.2 works on modern macs and it runs on top of windows that are already double buffered, so you end up with triple or quad buffering which is hugely expensive :(

**Comment by bradallred** [comment] 2017-09-16 22:36
I'm going to close this. I think everything works ok now; anything else can be a new issue.

**Comment by lynxlynxlynx** [comment] 2017-09-20 15:41
How do you know it works? I still can't see any video nor subtitles.

**Comment by bradallred** [comment] 2017-09-21 00:01
If you cant see video or subtitles that is certainly a separate issue, and one I cannot reproduce:
![image](https://user-images.githubusercontent.com/1126744/30673042-89f3f956-9e2d-11e7-8e0f-cf99bd69cc9a.png)

can you pinpoint the commit that broke it for you and open a new issue?

**Closed as completed by bradallred** 2017-09-21 00:01 UTC

**Comment by lynxlynxlynx** [comment] 2017-09-21 10:25
Are you sure you committed everything? It started above, with the window order changes.

**Comment by lynxlynxlynx** [comment] 2017-09-21 17:07
2770644 to be precise.

**Comment by lynxlynxlynx** [comment] 2017-09-22 19:37
tested on the laptop now. The subtitled movies render fine if the subs are off. Otherwise I get 1-2 frames per second (the rest are black, not that it's slow) and as the subs start, they draw over each other.

**Comment by bradallred** [comment] 2017-10-25 05:03
do you get a different result @ 640x480?

**Comment by lynxlynxlynx** [comment] 2017-10-25 07:59
Nope, that's even worse since iwd2 doesn't support that resolution.
